-- Stage 2 MVP Schema (HSQLDB / MySQL‑compatible)
-- Tables: users, decks, cards
-- Notes:
--  - Passwords are stored as BCrypt hashes (VARCHAR(72))
--  - Use UTC timestamps

-- Drop in safe order
DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS decks;
DROP TABLE IF EXISTS users;

-- USERS
CREATE TABLE users (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- HSQLDB
  -- For MySQL use: INT AUTO_INCREMENT PRIMARY KEY
  email        VARCHAR(255)  NOT NULL UNIQUE,
  display_name VARCHAR(120)  NOT NULL,
  password_hash VARCHAR(72)  NOT NULL,
  created_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- DECKS
CREATE TABLE decks (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id     INTEGER       NOT NULL,
  title        VARCHAR(140)  NOT NULL,
  description  VARCHAR(500),
  created_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);

-- CARDS
CREATE TABLE cards (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deck_id      INTEGER       NOT NULL,
  front_text   VARCHAR(1000) NOT NULL,
  back_text    VARCHAR(2000) NOT NULL,
  created_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (deck_id) REFERENCES decks(id) ON DELETE CASCADE
);

-- Indexes
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_decks_owner ON decks(owner_id);
CREATE INDEX idx_cards_deck ON cards(deck_id);

-- Seed data (use placeholder BCrypt hash for password 'Passw0rd!')
-- BCrypt example hash generated with 10 rounds:
-- $2a$10$6s6n5d9uVKd5wXx0s7mF8u4n9xqkDqO7a4i0v5I0YH9xZV2aB8y2C
-- Replace with your own generated hashes before production testing.
INSERT INTO users (email, display_name, password_hash) VALUES
('demo@team.local', 'Demo User', '$2a$10$6s6n5d9uVKd5wXx0s7mF8u4n9xqkDqO7a4i0v5I0YH9xZV2aB8y2C');

INSERT INTO decks (owner_id, title, description) VALUES
(1, 'Sample Deck', 'Getting started deck for demo');

INSERT INTO cards (deck_id, front_text, back_text) VALUES
(1, 'What is MVC?', 'Model-View-Controller: separates concerns.'),
(1, 'HTTP Status 200', 'OK: The request has succeeded.');
