-- Drop in safe order
DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS decks;
DROP TABLE IF EXISTS users;

-- USERS
CREATE TABLE users (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  email          VARCHAR(255)  NOT NULL,
  display_name   VARCHAR(120)  NOT NULL,
  password_hash  VARCHAR(72)   NOT NULL,
  created_at     TIMESTAMP,
  CONSTRAINT uq_users_email UNIQUE (email)
);

-- DECKS
CREATE TABLE decks (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  owner_id     INTEGER       NOT NULL,
  title        VARCHAR(140)  NOT NULL,
  description  VARCHAR(500),
  created_at   TIMESTAMP,
  FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);

-- CARDS
CREATE TABLE cards (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  deck_id      INTEGER       NOT NULL,
  front_text   VARCHAR(1000) NOT NULL,
  back_text    VARCHAR(2000) NOT NULL,
  created_at   TIMESTAMP,
  FOREIGN KEY (deck_id) REFERENCES decks(id) ON DELETE CASCADE
);

-- Indexes
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_decks_owner ON decks(owner_id);
CREATE INDEX idx_cards_deck ON cards(deck_id);

-- Seed user (replace hash later if you want)
INSERT INTO users (email, display_name, password_hash, created_at)
VALUES ('demo@team.local', 'Demo User', '$2a$10$6s6n5d9uVKd5wXx0s7mF8u4n9xqkDqO7a4i0v5I0YH9xZV2aB8y2C', CURRENT_TIMESTAMP);

INSERT INTO decks (owner_id, title, description, created_at)
VALUES (1, 'Sample Deck', 'Getting started deck for demo', CURRENT_TIMESTAMP);

INSERT INTO cards (deck_id, front_text, back_text, created_at)
VALUES
(1, 'What is MVC?', 'Model-View-Controller: separates concerns.', CURRENT_TIMESTAMP),
(1, 'HTTP Status 200', 'OK: The request has succeeded.', CURRENT_TIMESTAMP);
